<a href="https://colab.research.google.com/github/gplinkage/DataScienceBootCamp/blob/main/Class%20Notes/Instructor's%20notes/BDS35_26SEP_DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [22]:
df['Purchased'] = df['Purchased'].replace('Yes', 'Y')
df['Purchased'] = df['Purchased'].replace('No', 'N')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0         N
1    Spain  27.0  48000.0         Y
2  Germany  30.0  54000.0         N
3    Spain  38.0  61000.0         N
4  Germany  40.0      NaN         Y
5   France  35.0  58000.0         Y
6    Spain   NaN  52000.0         N
7   France  48.0  79000.0         Y
8  Germany  50.0  83000.0         N
9   France  37.0  67000.0         Y

In [25]:
mean_salary=df['Salary'].mean().round(1)
mean_salary

63777.8

In [30]:
df['Salary'] = df['Salary'].fillna(mean_salary)
df

Country   Age   Salary Purchased
0   France  44.0  72000.0         N
1    Spain  27.0  48000.0         Y
2  Germany  30.0  54000.0         N
3    Spain  38.0  61000.0         N
4  Germany  40.0  63777.8         Y
5   France  35.0  58000.0         Y
6    Spain   NaN  52000.0         N
7   France  48.0  79000.0         Y
8  Germany  50.0  83000.0         N
9   France  37.0  67000.0         Y

In [32]:
median_age =df['Age'].median()
median_age

38.0

In [34]:
df['Age'] = df['Age'].fillna(median_age)
df

Country   Age   Salary Purchased
0   France  44.0  72000.0         N
1    Spain  27.0  48000.0         Y
2  Germany  30.0  54000.0         N
3    Spain  38.0  61000.0         N
4  Germany  40.0  63777.8         Y
5   France  35.0  58000.0         Y
6    Spain  38.0  52000.0         N
7   France  48.0  79000.0         Y
8  Germany  50.0  83000.0         N
9   France  37.0  67000.0         Y

In [93]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [94]:
x = df.iloc[:, 0:3].values
y = df.iloc[:, -1].values

In [95]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [96]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

#Manage Missing Data#

In [97]:
from sklearn.impute import SimpleImputer

In [98]:
imputer_m = SimpleImputer(strategy = 'mean')
imputer_med = SimpleImputer(strategy = 'median')
imputer_mf = SimpleImputer(strategy = 'most_frequent')
imputer_cost = SimpleImputer(strategy = 'constant')

In [99]:
df['Salary'] = imputer_m.fit_transform(df[['Salary']]).round(0)
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [100]:
df['Age']= imputer_med.fit_transform(df[['Age']])
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [60]:
df['Age']= imputer_mf.fit_transform(df[['Age']])
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [62]:
df['Age']= imputer_cost.fit_transform(df[['Age']])
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [103]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [104]:
x = df.iloc[:, 0:3].values
y = df.iloc[:, -1].values

In [105]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
# imputer.fit(x[:, 1:3])
# x[:, 1:3]=imputer.transform(x[:,1:3]).round(0)
x[:, 1:3]=imputer.fit_transform(x[:,1:3]).round(0)
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63778.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [8]:
x = df.iloc[:, 0:3].values
y = df.iloc[:, -1].values

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'median')
# imputer.fit(x[:, 1:3])
x[:, 1:3]=imputer.fit_transform(x[:,1:3]).round(0)
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

#Encoding Catagorical data#

In [10]:
from matplotlib import transforms
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')

x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 61000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

#Encoding the Dependent Variable#

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

#Splitting the dataset into the Training set and Test set#

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [18]:
x_train, x_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 40.0, 61000.0],
        [1.0, 0.0, 0.0, 37.0, 67000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 0.0, 1.0, 38.0, 52000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [0.0, 0.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object),
 array([[0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

#Feature Selection#

In [23]:
# different data units

from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

x_train[:, 3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] =sc.fit_transform(x_test[:,3:])
x_train, x_test

(array([[0.0, 1.0, 0.0, 0.2797802353336846, -0.1310806262732691],
        [1.0, 0.0, 0.0, -0.23673712220542542, 0.49810637983842254],
        [0.0, 0.0, 1.0, -1.9584616473357923, -1.4943191395152677],
        [0.0, 0.0, 1.0, -0.06456466969238875, -1.0748611354408066],
        [1.0, 0.0, 0.0, 1.657159855437978, 1.7564803920618057],
        [0.0, 0.0, 1.0, -0.06456466969238875, -0.1310806262732691],
        [1.0, 0.0, 0.0, 0.9684700453858314, 1.022428884931499],
        [1.0, 0.0, 0.0, -0.5810820272314988, -0.44567412932911493]],
       dtype=object),
 array([[0.0, 1.0, 0.0, -1.0, -1.0],
        [0.0, 1.0, 0.0, 1.0, 1.0]], dtype=object))

In [24]:
df=pd.read_csv('/content/Data3.csv')
df

Country   Age   Salary Most_Freq Constant Purchased
0   France  44.0  72000.0      Pune    India        No
1    Spain  27.0  48000.0      Pune    India       Yes
2  Germany  30.0  54000.0    Mumbai    India        No
3    Spain  38.0  61000.0      Pune    India        No
4  Germany  40.0      NaN      Pune    India       Yes
5   France  35.0  58000.0    Nagpur    India       Yes
6    Spain   NaN  52000.0      Pune    India        No
7   France  48.0  79000.0       NaN    India       Yes
8  Germany  50.0  83000.0    Mumbai    India        No
9   France  37.0  67000.0      Pune      NaN       Yes

In [29]:
x = df.iloc[:, :5].values
x


array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, nan, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', nan, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, nan, 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', nan]], dtype=object)

In [30]:
y = df.iloc[:, -1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [35]:
from sklearn.impute import SimpleImputer
imputer_m = SimpleImputer(missing_values=np.nan, strategy= 'mean')
imputer_mf = SimpleImputer(missing_values=np.nan, strategy= 'most_frequent')
imputer_cost = SimpleImputer(missing_values=np.nan, strategy= 'constant',fill_value= 'India')

In [36]:
x[:, 1:3] = imputer_m.fit_transform(x[:, 1:3]).round(0)
x[:, 3:4] = imputer_mf.fit_transform(x[:, 3:4])
x[:, 4:5] = imputer_cost.fit_transform(x[:, 4:5])
x

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 63778.0, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 39.0, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, 'Pune', 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', 'India']], dtype=object)

In [43]:
from matplotlib import transforms
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct= ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0,3,4])], remainder='passthrough')
x= ct.fit_transform(x)
x


array([[0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 40.0, 63778.0],
       [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 35.0, 58000.0],
       [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 39.0, 52000.0],
       [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0],
       [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0]],
      dtype=object)

In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y= le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
x_train, x_test, y_train, y_test

(array([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 40.0, 63778.0],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 27.0, 48000.0],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 39.0, 52000.0],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 38.0, 61000.0],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
        [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 35.0, 58000.0]],
       dtype=object),
 array([[1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
        [1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0]],
       dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

In [49]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train[:, 9:] = sc.fit_transform(x_train[:,9:])
x_test[:,9:] =sc.fit_transform(x_test[:,9:])
x_train, x_test

(array([[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0,
         0.25819888974716115, 0.12383513383528294],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0,
         -0.25819888974716115, 0.461753237766921],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,
         -1.979524821394902, -1.5309357674165436],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,
         0.08606629658238704, -1.1114222926410773],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0,
         1.6352596350653539, 1.7202936620933198],
        [1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0,
         -0.08606629658238704, -0.16751697439627836],
        [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0,
         0.9467292624062575, 0.9861450812362538],
        [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
         -0.6024640760767093, -0.48215208047787805]], dtype=object),
 array([[1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, -1.0, -1.0],
        [1.0, 0.0, 0.0, 1.0