<a href="https://colab.research.google.com/github/gplinkage/DataScienceBootCamp/blob/main/Projects/California_Housing_Prices_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [320]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [321]:
df= pd.read_csv("/content/housing.csv")

In [ ]:
df

In [ ]:
df.describe()

In [323]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [324]:
df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)

In [ ]:
df.isna().sum()

In [326]:
x = df.iloc[:, [0,1,2,3,4,5,6,7,9]].values
print(x)

[[-122.23 37.88 41.0 ... 126.0 8.3252 'NEAR BAY']
 [-122.22 37.86 21.0 ... 1138.0 8.3014 'NEAR BAY']
 [-122.24 37.85 52.0 ... 177.0 7.2574 'NEAR BAY']
 ...
 [-121.22 39.43 17.0 ... 433.0 1.7 'INLAND']
 [-121.32 39.43 18.0 ... 349.0 1.8672 'INLAND']
 [-121.24 39.37 16.0 ... 530.0 2.3886 'INLAND']]


In [327]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder= 'passthrough')
x= ct.fit_transform(x)

In [348]:
print(x)

[[0.0 0.0 0.0 ... 322.0 126.0 8.3252]
 [0.0 0.0 0.0 ... 2401.0 1138.0 8.3014]
 [0.0 0.0 0.0 ... 496.0 177.0 7.2574]
 ...
 [0.0 1.0 0.0 ... 1007.0 433.0 1.7]
 [0.0 1.0 0.0 ... 741.0 349.0 1.8672]
 [0.0 1.0 0.0 ... 1387.0 530.0 2.3886]]


In [329]:
y = df.iloc[:, -2]
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...   
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [330]:
# Train and test data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [331]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [303]:
x_train

array([[-0.89150581,  1.46934754, -0.01348032, ..., -1.04760128,
        -1.1356496 ,  0.19001247],
       [-0.89150581, -0.68057418, -0.01348032, ...,  0.05210918,
        -0.13688171,  0.26931072],
       [ 1.12169768, -0.68057418, -0.01348032, ..., -0.35295521,
        -0.34343319,  0.02989505],
       ...,
       [-0.89150581, -0.68057418, -0.01348032, ..., -0.63116359,
        -0.27806879, -0.35589721],
       [ 1.12169768, -0.68057418, -0.01348032, ..., -0.32670914,
        -0.08197562,  0.92053182],
       [-0.89150581,  1.46934754, -0.01348032, ..., -0.35120548,
        -0.52645348, -1.30490629]])

In [332]:
x_test

array([[-0.88975652, -0.68715544, -0.02201661, ...,  0.11511818,
        -0.33869458,  0.1622391 ],
       [ 1.12390297, -0.68715544, -0.02201661, ..., -0.11903497,
        -0.18674914,  1.03200015],
       [-0.88975652,  1.45527481, -0.02201661, ...,  0.11787292,
         0.08832451,  0.2674461 ],
       ...,
       [-0.88975652,  1.45527481, -0.02201661, ..., -0.5285734 ,
        -0.45658328, -0.34488107],
       [-0.88975652,  1.45527481, -0.02201661, ..., -0.32472243,
        -0.33083533,  1.2264915 ],
       [ 1.12390297, -0.68715544, -0.02201661, ...,  0.03339414,
        -0.24700336, -0.2754733 ]])

In [334]:
y_train = y_train.values.reshape(-1, 1)
y_test = y_test.values.reshape(-1, 1)
y_train = sc.fit_transform(y_train)
y_test = sc.fit_transform(y_test)

In [335]:
y_train

array([[ 2.53052249],
       [ 0.54240803],
       [-0.09637901],
       ...,
       [ 0.70923604],
       [ 2.3973972 ],
       [-1.191566  ]])

In [336]:
y_test

array([[-0.59881772],
       [ 0.31544122],
       [-0.04010392],
       ...,
       [-0.67150305],
       [ 0.47482352],
       [-0.32996954]])

In [350]:
import tensorflow as tf

In [351]:
ann= tf.keras.models.Sequential()

In [352]:
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))

In [353]:
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))

In [354]:
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))

In [355]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [356]:
ann.compile(optimizer= 'adam', loss = 'binary_crossentropy', metrics= ['accuracy'])

In [359]:
ann.fit(x_train, y_train, batch_size=32, epochs=25)

Epoch 1/25
516/516 [==============================] - 3s 6ms/step - loss: -2773215.7500 - accuracy: 0.0000e+00
Epoch 2/25
516/516 [==============================] - 2s 3ms/step - loss: -3349926.7500 - accuracy: 0.0000e+00
Epoch 3/25
516/516 [==============================] - 2s 3ms/step - loss: -4005568.5000 - accuracy: 0.0000e+00
Epoch 4/25
516/516 [==============================] - 2s 3ms/step - loss: -4745527.0000 - accuracy: 0.0000e+00
Epoch 5/25
516/516 [==============================] - 2s 4ms/step - loss: -5577265.0000 - accuracy: 0.0000e+00
Epoch 6/25
516/516 [==============================] - 4s 9ms/step - loss: -6502276.5000 - accuracy: 0.0000e+00
Epoch 7/25
516/516 [==============================] - 3s 7ms/step - loss: -7528368.0000 - accuracy: 0.0000e+00
Epoch 8/25
516/516 [==============================] - 3s 6ms/step - loss: -8667500.0000 - accuracy: 0.0000e+00
Epoch 9/25
516/516 [==============================] - 3s 5ms/step - loss: -9919751.0000 - accuracy: 0.0000e+00
E