<a href="https://colab.research.google.com/github/gplinkage/DataScienceBootCamp/blob/main/Class%20Notes/Exercise/My%20OwnExcercise/Data_Preprosessing_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
mean_salary = df['Salary'].mean().round(1)
mean_salary

63777.8

In [8]:
median_age = df['Age'].median().round(1)
median_age

38.0

In [17]:
from sklearn.impute import SimpleImputer
impute_mean = SimpleImputer(strategy= 'mean')
impute_median = SimpleImputer(strategy= 'median')

In [33]:
df['Salary'] = impute_mean.fit_transform(df[['Salary']]).round(0)
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [34]:
df['Age'] = impute_median.fit_transform(df[['Age']])
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [36]:
x= df.iloc[: , :3].values
y = df.iloc[:, -1].values

In [37]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63778.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [38]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')

x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63778.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [41]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,  test_size = 0.2, random_state=0)

In [46]:
x_train, x_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 40.0, 63778.0],
        [1.0, 0.0, 0.0, 37.0, 67000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 0.0, 1.0, 38.0, 52000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [0.0, 0.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object),
 array([[0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

In [47]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

x_train[:, 3:]= sc.fit_transform(x_train[:, 3:])
x_test[:, 3:]= sc.fit_transform(x_test[:, 3:])

x_train, x_test


(array([[0.0, 1.0, 0.0, 0.27978023533368457, 0.12383513383528294],
        [1.0, 0.0, 0.0, -0.23673712220542542, 0.461753237766921],
        [0.0, 0.0, 1.0, -1.958461647335792, -1.5309357674165436],
        [0.0, 0.0, 1.0, -0.06456466969238875, -1.1114222926410773],
        [1.0, 0.0, 0.0, 1.6571598554379778, 1.7202936620933198],
        [0.0, 0.0, 1.0, -0.06456466969238875, -0.16751697439627836],
        [1.0, 0.0, 0.0, 0.9684700453858313, 0.9861450812362538],
        [1.0, 0.0, 0.0, -0.5810820272314987, -0.48215208047787805]],
       dtype=object),
 array([[0.0, 1.0, 0.0, -1.0, -1.0],
        [0.0, 1.0, 0.0, 1.0, 1.0]], dtype=object))

In [103]:
df=pd.read_csv('/content/Data3.csv')
df

Country   Age   Salary Most_Freq Constant Purchased
0   France  44.0  72000.0      Pune    India        No
1    Spain  27.0  48000.0      Pune    India       Yes
2  Germany  30.0  54000.0    Mumbai    India        No
3    Spain  38.0  61000.0      Pune    India        No
4  Germany  40.0      NaN      Pune    India       Yes
5   France  35.0  58000.0    Nagpur    India       Yes
6    Spain   NaN  52000.0      Pune    India        No
7   France  48.0  79000.0       NaN    India       Yes
8  Germany  50.0  83000.0    Mumbai    India        No
9   France  37.0  67000.0      Pune      NaN       Yes

In [104]:
x= df.iloc[: , :5].values
y= df.iloc[:, -1].values


In [105]:
x

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, nan, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', nan, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, nan, 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', nan]], dtype=object)

In [106]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [83]:
from sklearn.impute import SimpleImputer
impute_mean = SimpleImputer(missing_values=np.nan, strategy = 'mean')
impute_median = SimpleImputer(missing_values=np.nan, strategy = 'median')
impute_mf = SimpleImputer(missing_values=np.nan, strategy = 'most_frequent')
impute_cost = SimpleImputer(missing_values=np.nan, strategy = 'constant', fill_value = 'India')

In [107]:
x[:, 4:5] = impute_cost.fit_transform(x[:, 4:5])
x[:, 3:4] = impute_mf.fit_transform(x[:, 3:4])
x[:, 2:3] = impute_mean.fit_transform(x[:, 2:3]).round(0)
x[:, 1:2] = impute_median.fit_transform(x[:, 1:2])

In [108]:
x

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 63778.0, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 38.0, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, 'Pune', 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', 'India']], dtype=object)

In [97]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct= ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0, 3, 4])], remainder= 'passthrough')
x= ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 63778.0],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 52000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0]], dtype=object)

In [98]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y= le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [100]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state=42)
x_train, x_test, y_train, y_test

(array([[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0],
        [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 63778.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 52000.0]], dtype=object),
 array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0]], dtype=object),
 array([1, 0, 1, 0, 1, 1, 0, 0]),
 array([0, 1]))

In [102]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train[:, 7:] = sc.fit_transform(x_train[:, 7:])
x_test[:, 7:] = sc.fit_transform(x_test[:, 7:])
x_train, x_test

(array([[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, -0.7327979531190473,
         -0.6260409276152965],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0259171343666662,
         1.0130395318010672],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.8075682843603167,
         1.832579761509249],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, -1.7098618906111103,
         -1.094349630305686],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, -0.3419723781222221,
         0.42765365343808015],
        [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.24426598437301575,
         0.050430993420971335],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, -0.14655959062380947,
         -0.27480940059750425],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, -0.14655959062380947,
         -1.328503981650881]], dtype=object),
 array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, -1.0, -1.0]], dtype=object))